AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  zip:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: cloudfront.lambda_handler
      Runtime: python3.8
